contact/urls.py
from django.urls import path
from contact.views import (
    home,
    enroll,
    social,
    thanks,
    failed,
)

app_name = 'contact'

urlpatterns = [
    path('', home, name='home'),
    path('enroll/step-1/', enroll, name='enroll'),
    path('enroll/step-2/', social, name='social'),
    path('enroll/success/waiting/', thanks, name='thanks'),
    path('enroll/failed/', failed, name='failed'),
]

learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

class EnrollForDemo(models.Model):
    """
    This model contains the data about the students who have registered for the demo of the learning platform.
    """
    STUDENT_CHOICES = [
        ('school', 'School Student'),
        ('college', 'College Student'),
        ('self', 'Self Learner'),
        ('working', 'Working Person'),
        ('other', 'Other')
    ]
    first_name = models.CharField(max_length=124, null=True)
    last_name = models.CharField(max_length=124, null=True)
    email = models.EmailField(null=True)
    father_name = models.CharField(max_length=255, null=True)
    mobile_number = models.CharField(max_length=10, null=True)
    student = models.CharField(max_length=124, null=True, choices=STUDENT_CHOICES, default="school")
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['first_name', 'last_name', 'father_name']
        verbose_name = 'Enrollment for Demo'
        verbose_name_plural = 'Enrollements for Demo'

    def __str__(self):
        return "{} - {} {}".format(str(self.id), self.first_name, self.last_name)

contact/forms.py
from django import forms
from contact.models import EnrollForDemo

class EnrollForDemoForm(forms.ModelForm):
    class Meta:
        model = EnrollForDemo
        fields = ['first_name', 'last_name', 'father_name', 'email', 'mobile_number', 'student']

contact/views.py
from django.shortcuts import render, redirect

from contact.forms import EnrollForDemoForm

# Create your views here.
def home(request):
    context = {}
    return render(request, 'contact/home.html', context)


def enroll(request):
    if request.method == 'POST':
        form = EnrollForDemoForm(request.POST or None)
        if form.is_valid():
            enroll = form.save(commit=False)
            enroll.save()
            return redirect('contact:social')
    else:
        form = EnrollForDemoForm()
    context = {
        'form': form
    }
    return render(request, 'contact/enroll.html', context)


def social(request):
    context = {}
    return render(request, 'contact/social.html', context)


def thanks(request):
    context = {}
    return render(request, 'contact/thanks.html', context)


def failed(request):
    context = {}
    return render(request, 'contact/failed.html', context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet"> 

    <title>{% block title %}{% endblock %} - RightBros Learners Community</title>

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block style %}
    {% endblock style %}
  </head>
  <body>

    {% include 'includes/navbar.html' %}

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="{% static 'js/main.js' %}"></script>

    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

templates/contact/enroll.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Enroll for the Demo{% endblock %}

{% block style %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css"
    rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/enroll.css' %}">
{% endblock style %}

{% block content %}
<div class="registration-form">

    <form method="POST">
        {% csrf_token %}
        <div class="form-icon">
            <span><i class="icon icon-user"></i></span>
        </div>
        {{ form|crispy }}
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-primary create-account">
        </div>
    </form>
    <div class="social-media">
        <h5>Sign up with social media</h5>
        <div class="social-icons">
            <a href="#"><i class="icon-social-facebook" title="Facebook"></i></a>
            <a href="#"><i class="icon-social-google" title="Google"></i></a>
            <a href="#"><i class="icon-social-twitter" title="Twitter"></i></a>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js">
</script>
<script src="{% static 'js/enroll.js' %}"></script>

{% endblock javascript %}

templates/contact/failed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

templates/contact/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

templates/contact/social.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

templates/contact/thanks.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

templates/includes/navbar.html
<nav class="learn-navbar">
    <h3 class="learn-logo">RIGHTBROS Learners</h3>

    <div class="learn-icon"><i class="fa fa-bars"></i></div>

    <div class="learn-links-wrapper active">
        <div class="learn-backdrop"></div>
        <div class="learn-close-btn"><i class="fa fa-times"></i></div>
        <ul class="learn-links">
            <li><a href="{% url 'contact:home' %}">Home</a></li>
            <li><a href="{% url 'contact:enroll' %}">Enroll</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
</nav>